pipeline:
  identifier: Build_StuartGrimes_flow_even_1752610687338
  name: Build flow-even
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: StuartGrimes/flow-even
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
